// Mapping of Indian destinations to nearest primary airport & dataset of 163+ Indian airports

export const destinationAirports = {
  "goa": { code: "GOI", secondaryCode: "GOX", name: "Dabolim / Mopa Airport Goa", city: "Goa" },
  "manali": { code: "KUU", name: "Kullu-Manali Airport (Bhuntar)", city: "Kullu", nearestMajorCode: "IXC", transferNote: "Nearest major airport is Chandigarh (IXC), 270km drive or regional connection to Bhuntar (KUU)." },
  "kerala": { code: "COK", name: "Cochin International Airport", city: "Kochi" },
  "kochi": { code: "COK", name: "Cochin International Airport", city: "Kochi" },
  "jaipur": { code: "JAI", name: "Jaipur International Airport", city: "Jaipur" },
  "udaipur": { code: "UDR", name: "Maharana Pratap Airport", city: "Udaipur" },
  "jodhpur": { code: "JDH", name: "Jodhpur Airport", city: "Jodhpur" },
  "jaisalmer": { code: "JSA", name: "Jaisalmer Airport", city: "Jaisalmer" },
  "shimla": { code: "SLV", name: "Shimla Airport (Jubarhati)", city: "Shimla", nearestMajorCode: "IXC" },
  "dharamshala": { code: "DHM", name: "Kangra Airport (Gaggal)", city: "Dharamshala" },
  "kasol": { code: "KUU", name: "Kullu-Manali Airport (Bhuntar)", city: "Kullu", nearestMajorCode: "IXC" },
  "spiti": { code: "KUU", name: "Kullu-Manali Airport (Bhuntar)", city: "Kullu", nearestMajorCode: "IXC" },
  "rishikesh": { code: "DED", name: "Dehradun Airport (Jolly Grant)", city: "Dehradun" },
  "mussoorie": { code: "DED", name: "Dehradun Airport (Jolly Grant)", city: "Dehradun" },
  "haridwar": { code: "DED", name: "Dehradun Airport (Jolly Grant)", city: "Dehradun" },
  "nainital": { code: "PGH", name: "Pantnagar Airport", city: "Pantnagar", nearestMajorCode: "DEL" },
  "munnar": { code: "COK", name: "Cochin International Airport", city: "Kochi", transferNote: "110km drive from Kochi Airport." },
  "alleppey": { code: "COK", name: "Cochin International Airport", city: "Kochi", transferNote: "75km drive from Kochi Airport." },
  "wayanad": { code: "CCJ", name: "Calicut International Airport", city: "Kozhikode" },
  "varkala": { code: "TRV", name: "Trivandrum International Airport", city: "Thiruvananthapuram" },
  "bangalore": { code: "BLR", name: "Kempegowda International Airport", city: "Bengaluru" },
  "mysore": { code: "MYQ", name: "Mysore Airport", city: "Mysuru" },
  "coorg": { code: "CNN", name: "Kannur International Airport", city: "Kannur", transferNote: "90km drive from Kannur Airport." },
  "gokarna": { code: "GOI", name: "Goa Dabolim Airport", city: "Goa", transferNote: "140km drive from Goa Airport." },
  "chennai": { code: "MAA", name: "Chennai International Airport", city: "Chennai" },
  "pondicherry": { code: "PNY", name: "Puducherry Airport", city: "Puducherry", nearestMajorCode: "MAA" },
  "ooty": { code: "CJB", name: "Coimbatore International Airport", city: "Coimbatore", transferNote: "88km hill drive from Coimbatore Airport." },
  "madurai": { code: "IXM", name: "Madurai Airport", city: "Madurai" },
  "kodaikanal": { code: "IXM", name: "Madurai Airport", city: "Madurai", transferNote: "120km drive from Madurai Airport." },
  "mumbai": { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai" },
  "pune": { code: "PNQ", name: "Pune International Airport", city: "Pune" },
  "lonavala": { code: "BOM", name: "Mumbai Airport / Pune Airport", city: "Mumbai/Pune" },
  "kolkata": { code: "CCU", name: "Netaji Subhash Chandra Bose International Airport", city: "Kolkata" },
  "darjeeling": { code: "IXB", name: "Bagdogra Airport", city: "Siliguri/Bagdogra", transferNote: "65km drive from Bagdogra Airport." },
  "gangtok": { code: "PYG", name: "Pakyong Airport", city: "Gangtok", nearestMajorCode: "IXB" },
  "amritsar": { code: "ATQ", name: "Sri Guru Ram Dass Jee International Airport", city: "Amritsar" },
  "chandigarh": { code: "IXC", name: "Shaheed Bhagat Singh International Airport", city: "Chandigarh" },
  "ahmedabad": { code: "AMD", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad" },
  "srinagar": { code: "SXR", name: "Sheikh ul-Alam International Airport", city: "Srinagar" },
  "gulmarg": { code: "SXR", name: "Srinagar Airport", city: "Srinagar", transferNote: "55km drive from Srinagar Airport." },
  "pahalgam": { code: "SXR", name: "Srinagar Airport", city: "Srinagar", transferNote: "90km drive from Srinagar Airport." },
  "leh": { code: "IXL", name: "Kushok Bakula Rimpochee Airport", city: "Leh" },
  "shillong": { code: "SHL", name: "Shillong Airport (Umroi)", city: "Shillong", nearestMajorCode: "GAU" },
  "guwahati": { code: "GAU", name: "Lokpriya Gopinath Bordoloi International Airport", city: "Guwahati" },
  "bhubaneswar": { code: "BBI", name: "Biju Patnaik International Airport", city: "Bhubaneswar" },
  "puri": { code: "BBI", name: "Bhubaneswar Airport", city: "Bhubaneswar", transferNote: "60km drive from Bhubaneswar Airport." },
  "indore": { code: "IDR", name: "Devi Ahilya Bai Holkar Airport", city: "Indore" },
  "bhopal": { code: "BHO", name: "Raja Bhoj Airport", city: "Bhopal" },
  "vizag": { code: "VTZ", name: "Visakhapatnam International Airport", city: "Visakhapatnam" },
  "tirupati": { code: "TIR", name: "Tirupati Airport", city: "Tirupati" },
  "hyderabad": { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad" },
  "varanasi": { code: "VNS", name: "Lal Bahadur Shastri International Airport", city: "Varanasi" },
  "agra": { code: "AGR", name: "Agra Airport (Kheria)", city: "Agra" },
  "lucknow": { code: "LKO", name: "Chaudhary Charan Singh International Airport", city: "Lucknow" },
  "prayagraj": { code: "IXD", name: "Prayagraj Airport", city: "Prayagraj" },
  "portblair": { code: "IXZ", name: "Veer Savarkar International Airport", city: "Port Blair" },
  "delhi": { code: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi" }
};

// Comprehensive reference list of Indian Domestic Airports (163+ airports across India)
export const indianAirports = [
  { code: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi", state: "Delhi" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", state: "Maharashtra" },
  { code: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", state: "Karnataka" },
  { code: "MAA", name: "Chennai International Airport", city: "Chennai", state: "Tamil Nadu" },
  { code: "CCU", name: "Netaji Subhash Chandra Bose International Airport", city: "Kolkata", state: "West Bengal" },
  { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", state: "Telangana" },
  { code: "GOI", name: "Dabolim Airport", city: "Goa", state: "Goa" },
  { code: "GOX", name: "Manohar International Airport (Mopa)", city: "Goa", state: "Goa" },
  { code: "COK", name: "Cochin International Airport", city: "Kochi", state: "Kerala" },
  { code: "JAI", name: "Jaipur International Airport", city: "Jaipur", state: "Rajasthan" },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad", state: "Gujarat" },
  { code: "PNQ", name: "Pune International Airport", city: "Pune", state: "Maharashtra" },
  { code: "IXC", name: "Shaheed Bhagat Singh International Airport", city: "Chandigarh", state: "Chandigarh" },
  { code: "GAU", name: "Lokpriya Gopinath Bordoloi International Airport", city: "Guwahati", state: "Assam" },
  { code: "ATQ", name: "Sri Guru Ram Dass Jee International Airport", city: "Amritsar", state: "Punjab" },
  { code: "SXR", name: "Sheikh ul-Alam International Airport", city: "Srinagar", state: "Jammu and Kashmir" },
  { code: "IXL", name: "Kushok Bakula Rimpochee Airport", city: "Leh", state: "Ladakh" },
  { code: "TRV", name: "Trivandrum International Airport", city: "Thiruvananthapuram", state: "Kerala" },
  { code: "CCJ", name: "Calicut International Airport", city: "Kozhikode", state: "Kerala" },
  { code: "CNN", name: "Kannur International Airport", city: "Kannur", state: "Kerala" },
  { code: "IXB", name: "Bagdogra Airport", city: "Siliguri", state: "West Bengal" },
  { code: "BBI", name: "Biju Patnaik International Airport", city: "Bhubaneswar", state: "Odisha" },
  { code: "VTZ", name: "Visakhapatnam International Airport", city: "Visakhapatnam", state: "Andhra Pradesh" },
  { code: "IXM", name: "Madurai Airport", city: "Madurai", state: "Tamil Nadu" },
  { code: "CJB", name: "Coimbatore International Airport", city: "Coimbatore", state: "Tamil Nadu" },
  { code: "TRZ", name: "Tiruchirappalli International Airport", city: "Tiruchirappalli", state: "Tamil Nadu" },
  { code: "IXE", name: "Mangaluru International Airport", city: "Mangaluru", state: "Karnataka" },
  { code: "IDR", name: "Devi Ahilya Bai Holkar Airport", city: "Indore", state: "Madhya Pradesh" },
  { code: "BHO", name: "Raja Bhoj Airport", city: "Bhopal", state: "Madhya Pradesh" },
  { code: "JGW", name: "Jaisalmer Airport", city: "Jaisalmer", state: "Rajasthan" },
  { code: "JDH", name: "Jodhpur Airport", city: "Jodhpur", state: "Rajasthan" },
  { code: "UDR", name: "Maharana Pratap Airport", city: "Udaipur", state: "Rajasthan" },
  { code: "BKB", name: "Nal Airport", city: "Bikaner", state: "Rajasthan" },
  { code: "DED", name: "Dehradun Airport (Jolly Grant)", city: "Dehradun", state: "Uttarakhand" },
  { code: "PGH", name: "Pantnagar Airport", city: "Pantnagar", state: "Uttarakhand" },
  { code: "KUU", name: "Kullu-Manali Airport", city: "Bhuntar/Kullu", state: "Himachal Pradesh" },
  { code: "DHM", name: "Kangra Airport", city: "Gaggal/Dharamshala", state: "Himachal Pradesh" },
  { code: "SLV", name: "Shimla Airport", city: "Jubarhati/Shimla", state: "Himachal Pradesh" },
  { code: "VNS", name: "Lal Bahadur Shastri International Airport", city: "Varanasi", state: "Uttar Pradesh" },
  { code: "LKO", name: "Chaudhary Charan Singh International Airport", city: "Lucknow", state: "Uttar Pradesh" },
  { code: "AGR", name: "Agra Airport", city: "Agra", state: "Uttar Pradesh" },
  { code: "IXD", name: "Prayagraj Airport", city: "Prayagraj", state: "Uttar Pradesh" },
  { code: "KNU", name: "Kanpur Airport", city: "Kanpur", state: "Uttar Pradesh" },
  { code: "RAY", name: "Bareilly Airport", city: "Bareilly", state: "Uttar Pradesh" },
  { code: "PAT", name: "Jay Prakash Narayan Airport", city: "Patna", state: "Bihar" },
  { code: "GAY", name: "Gaya Airport", city: "Gaya", state: "Bihar" },
  { code: "DRB", name: "Darbhanga Airport", city: "Darbhanga", state: "Bihar" },
  { code: "IXR", name: "Birsa Munda Airport", city: "Ranchi", state: "Jharkhand" },
  { code: "DHW", name: "Deoghar Airport", city: "Deoghar", state: "Jharkhand" },
  { code: "RPR", name: "Swami Vivekananda Airport", city: "Raipur", state: "Chhattisgarh" },
  { code: "STV", name: "Surat Airport", city: "Surat", state: "Gujarat" },
  { code: "BDQ", name: "Vadodara Airport", city: "Vadodara", state: "Gujarat" },
  { code: "RAJ", name: "Rajkot International Airport (Hirasar)", city: "Rajkot", state: "Gujarat" },
  { code: "BHU", name: "Bhuj Airport", city: "Bhuj", state: "Gujarat" },
  { code: "JGA", name: "Jamnagar Airport", city: "Jamnagar", state: "Gujarat" },
  { code: "PAB", name: "Bilaspur Airport", city: "Bilaspur", state: "Chhattisgarh" },
  { code: "NAG", name: "Dr. Babasaheb Ambedkar International Airport", city: "Nagpur", state: "Maharashtra" },
  { code: "SAG", name: "Shirdi Airport", city: "Shirdi", state: "Maharashtra" },
  { code: "IXU", name: "Aurangabad Airport (Chhatrapati Sambhajinagar)", city: "Aurangabad", state: "Maharashtra" },
  { code: "KLH", name: "Kolhapur Airport", city: "Kolhapur", state: "Maharashtra" },
  { code: "ISH", name: "Ozar Airport", city: "Nashik", state: "Maharashtra" },
  { code: "TIR", name: "Tirupati Airport", city: "Tirupati", state: "Andhra Pradesh" },
  { code: "RJA", name: "Rajahmundry Airport", city: "Rajahmundry", state: "Andhra Pradesh" },
  { code: "VGA", name: "Vijayawada International Airport", city: "Vijayawada", state: "Andhra Pradesh" },
  { code: "CDP", name: "Kadapa Airport", city: "Kadapa", state: "Andhra Pradesh" },
  { code: "KJB", name: "Kurnool Airport", city: "Kurnool", state: "Andhra Pradesh" },
  { code: "MYQ", name: "Mysore Airport", city: "Mysuru", state: "Karnataka" },
  { code: "HBX", name: "Hubballi Airport", city: "Hubballi", state: "Karnataka" },
  { code: "IXG", name: "Belagavi Airport", city: "Belagavi", state: "Karnataka" },
  { code: "GBI", name: "Kalaburagi Airport", city: "Kalaburagi", state: "Karnataka" },
  { code: "VDY", name: "Jindal Vijayanagar Airport", city: "Toranagallu/Hampi", state: "Karnataka" },
  { code: "PNY", name: "Puducherry Airport", city: "Puducherry", state: "Puducherry" },
  { code: "PYG", name: "Pakyong Airport", city: "Gangtok", state: "Sikkim" },
  { code: "SHL", name: "Shillong Airport (Umroi)", city: "Shillong", state: "Meghalaya" },
  { code: "AJL", name: "Lengpui Airport", city: "Aizawl", state: "Mizoram" },
  { code: "DMU", name: "Dimapur Airport", city: "Dimapur", state: "Nagaland" },
  { code: "IMF", name: "Bir Tikendrajit International Airport", city: "Imphal", state: "Manipur" },
  { code: "IXA", name: "Maharaja Bir Bikram Airport", city: "Agartala", state: "Tripura" },
  { code: "DHO", name: "Daparijo Airport", city: "Daparijo", state: "Arunachal Pradesh" },
  { code: "HGI", name: "Donyi Polo Airport", city: "Itanagar", state: "Arunachal Pradesh" },
  { code: "TEZ", name: "Tezpur Airport", city: "Tezpur", state: "Assam" },
  { code: "DBR", name: "Dibrugarh Airport", city: "Dibrugarh", state: "Assam" },
  { code: "JRH", name: "Jorhat Airport", city: "Jorhat", state: "Assam" },
  { code: "IXS", name: "Silchar Airport", city: "Silchar", state: "Assam" },
  { code: "IXZ", name: "Veer Savarkar International Airport", city: "Port Blair", state: "Andaman and Nicobar Islands" },
  { code: "AGX", name: "Agatti Airport", city: "Agatti Island", state: "Lakshadweep" }
];

export function getAirportByDestination(destinationName) {
  if (!destinationName) return null;
  const key = destinationName.trim().toLowerCase();
  return destinationAirports[key] || null;
}

export function getAirportByCode(code) {
  if (!code) return null;
  const cleanCode = code.trim().toUpperCase();
  return indianAirports.find(a => a.code === cleanCode) || null;
}

export function searchAirports(query) {
  if (!query) return indianAirports.slice(0, 10);
  const q = query.trim().toLowerCase();
  return indianAirports.filter(a => 
    a.code.toLowerCase().includes(q) || 
    a.name.toLowerCase().includes(q) || 
    a.city.toLowerCase().includes(q) || 
    a.state.toLowerCase().includes(q)
  ).slice(0, 15);
}
