const fs = require('fs');

const locationMap = {
  "Manali to Leh": "leh",
  "Spiti Valley Circuit": "spiti",
  "Coorg to Ooty": "coorg",
  "Rajasthan Royal Route": "rajasthan",
  "Zanskar Valley": null,
  "North East Circuit": null,
  "Konkan Coast Route": "konkan",
  "Munnar to Thekkady": "munnar",
  "Rann of Kutch Route": "rannofkutch",
  "Sandakphu Trek Route": null,
  "Tawang Circuit": "tawang",
  "Khardung La Pass": "leh",
  "Chopta": "chopta",
  "Munsiyari": null,
  "Spiti Valley": "spiti",
  "Tirthan Valley": null,
  "Dzükou Valley": null,
  "Sandakphu": null,
  "Har Ki Dun": null,
  "Ziro Valley": "zirovalley",
  "Tawang": "tawang",
  "Chitkul": null,
  "Mechuka": null,
  "Pin Valley": null,
  "Darjeeling Toy Train": "darjeeling",
  "Konkan Railway": "konkan",
  "Kalka Shimla Railway": "shimla",
  "Palace on Wheels": "rajasthan",
  "Nilgiri Mountain Railway": "ooty",
  "Matheran Hill Railway": null,
  "Kangra Valley Railway": null,
  "Vistadome Train Kerala": "kerala",
  "Deccan Odyssey": "mumbai",
  "Mandovi Express": "goa",
  "Shimla to Kalka": "shimla",
  "Rishikesh": "rishikesh",
  "Coorg": "coorg",
  "Pushkar": "pushkar",
  "Munnar": "munnar",
  "Kasol": "kasol",
  "Lansdowne": null,
  "Matheran": null,
  "Hampi": "hampi",
  "Vaarkala": "varkala",
  "Pondicherry": "pondicherry",
  "Lonavala": "lonavala",
  "Mcleod Ganj": "dharamshala",
  "Alleppey": "alleppey",
  "Nainital": "nainital",
  "Gokarna": "gokarna",
  "Goa (off-season)": "goa",
  "Varanasi": "varanasi",
  "Mathura Vrindavan": "mathura",
  "Kerala Backwaters": "alleppey",
  "Cherrapunji": "cherrapunji",
  "Goa Monsoon": "goa",
  "Valley of Flowers": null,
  "Mawsynram": null,
  "Wayanad": "wayanad",
  "Kudremukh": null,
  "Agumbe": null,
  "Gulmarg": "gulmarg",
  "Auli": "auli",
  "Manali": "manali",
  "Leh Ladakh": "leh",
  "Dhanaulti": null,
  "Kufri": null,
  "Rohtang Pass": "manali",
  "Radhanagar Beach": "havelock",
  "Varkala": "varkala",
  "Goa Beaches": "goa",
  "Puri Beach": "puri",
  "Kovalam Beach": "kerala",
  "Tarkarli": "konkan",
  "Mandrem Beach": "goa",
  "Neil Island": "neilisland",
  "Dhanushkodi": "rameswaram",
  "Marari Beach": "alleppey",
  "Agonda Beach": "goa",
  "Bangaram Island": "bangaram",
  "Havelock Island": "havelock",
  "Magnetic Hill": "leh",
  "Hawa Mahal": "jaipur",
  "Dal Lake": "srinagar",
  "Tsomgo Lake": "gangtok",
  "Dudhsagar Falls": "goa",
  "Hampi Ruins": "hampi",
  "Pangong Lake": "pangonglake",
  "Majuli Island": "majuli",
  "Chettinad": null,
  "Andaman": "portblair",
  "Bir Billing": "birbilling",
  "Dandeli": "dandeli",
  "Kevadia": null,
  "Amritsar": "amritsar",
  "Kolkata": "kolkata",
  "Hyderabad": "hyderabad",
  "Mumbai": "mumbai",
  "Lucknow": "lucknow",
  "Chennai": "chennai",
  "Indore": "indore",
  "Mangalore": null,
  "Onam": "kerala",
  "Holi in Mathura": "mathura",
  "Hornbill Festival": "kohima",
  "Rann Utsav": "rannofkutch",
  "Thrissur Pooram": "kerala",
  "Desert Festival Jaisalmer": "jaisalmer",
  "Hemis Festival": "leh",
  "Ganesh Chaturthi Mumbai": "mumbai",
  "Durga Puja Kolkata": "kolkata",
  "Diwali Varanasi": "varanasi",
  "Zanskar Winter Chadar Trek": "leh",
  "Bihu Festival": "guwahati",
  "Kala Ghoda Arts Festival": "mumbai",
  "Goa": "goa",
  "Rajasthan": "rajasthan",
  "Kerala": "kerala"
};

let content = fs.readFileSync('../src/data/exploreData.js', 'utf8');
const lines = content.split('\n');
const outLines = [];

for (let line of lines) {
  if (line.includes('{ name: "')) {
    const nameMatch = line.match(/{ name: "([^"]+)"/);
    if (nameMatch) {
      const name = nameMatch[1];
      const newKey = locationMap[name];
      if (newKey) {
        line = line.replace(/available: false/, 'available: true, locationKey: "' + newKey + '"');
        line = line.replace(/available: true,\s*locationKey: "[^"]+"/, 'available: true, locationKey: "' + newKey + '"');
      }
    }
  }
  outLines.push(line);
}

fs.writeFileSync('../src/data/exploreData.js', outLines.join('\n'));
console.log('Successfully updated exploreData.js');
